#!/bin/sh

#
# Copyright © 2015-present The Gradle Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, set POSIX_SHELL to such a shell, or configure the script
#       to use a compliant shell.
#       See https://www.gnu.org/software/autoconf/manual/autoconf/2.71/html_node/Posix-Variants.html
#   (2) All the variables in "Environment variables" section below must be
#       exported.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
if ( command -v readlink >/dev/null 2>&1 && readlink -f "$0" >/dev/null 2>&1 ); then
    # readlink -f is not available on all platforms, notably macOS.
    # However, readlink -f is not needed on platforms with a symlink
    # to a file in the same directory, so we fall back to readlink
    # without -f in that case.
    if APP_HOME=$(readlink -f "$0") >/dev/null 2>&1; then
        # This is still a relative path in the unlikely event that the
        # current directory is not in $PATH, so we resolve that:
        APP_HOME=$(dirname "$APP_HOME")
    elif APP_HOME=$(readlink "$0"); then
        # readlink without -f was available, but the result might be relative
        if [ "${APP_HOME#/}" = "$APP_HOME" ]; then
            # The link was relative, so resolve it
            APP_HOME=$(cd "$(dirname "$0")" && pwd -P)/$APP_HOME
        fi
        # Now we have a path, so get the directory
        APP_HOME=$(dirname "$APP_HOME")
    else
        # readlink was not available at all, so we'll just take $0 as-is
        APP_HOME="$0"
    fi
else
    # readlink not available at all, so we'll just take $0 as-is
    APP_HOME="$0"
fi

# Change from the installation directory to the directory where the script is located
cd "$(dirname "$APP_HOME")" || exit

# Use the maximum available stack size for sub processes
ulimit -s unlimited 2>/dev/null || true

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

# Use the JAVA_OPTS and GRADLE_OPTS only for JVM options for sub processes
export DEFAULT_JVM_OPTS
export JAVA_OPTS
export GRADLE_OPTS

# Collect all arguments for the java command:
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, $GRADLE_OPTS as the default options
#   * -Dorg.gradle.appname as the application name
#   * The -classpath option to point to the correct classpath
#   * The main class to run
#   * The custom file arguments
#   * The main args
exec java \
    $DEFAULT_JVM_OPTS \
    $JAVA_OPTS \
    $GRADLE_OPTS \
    -Dorg.gradle.appname="$(basename "$0")" \
    -classpath "$(dirname "$0")/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"